name: Routine de mise a jour du graphique

on:
  schedule:
    - cron: '0 6 * * *'
  workflow_dispatch:

# ÉTAPE CRUCIALE : Donne le droit à l'action de publier sur GitHub Pages
permissions:
  contents: write
  pages: write
  id-token: write

concurrency:
  group: "pages"
  cancel-in-progress: false

jobs:
  run-script:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest

    steps:
    - name: Checkout du code
      uses: actions/checkout@v4

    - name: Configuration de Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.10'

    - name: Installation des modules Python
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Creation du graphique
      run: python generate_chart.py

    - name: Sauvegarde de l'image sur GitHub
      run: |
        git config --local user.email "actions@github.com"
        git config --local user.name "GitHub Actions Bot"
        git add index.html
        git diff-index --quiet HEAD || (git commit -m "Mise à jour du graphique HTML" && git push)

    # NOUVELLES ÉTAPES : Publie automatiquement le fichier index.html sur le web
    - name: Configurer Pages
      uses: actions/configure-pages@v5

    - name: Televerser le site web
      uses: actions/upload-pages-artifact@v3
      with:
        path: '.' # Publie la racine du dépôt où se trouve index.html

    - name: Deployer sur GitHub Pages
      id: deployment
      uses: actions/deploy-pages@v4
